### PR TITLE
Feature/4 - Fixed Vertical Wire Bugs

### PR DESCRIPTION
**Pull request by HoferC**
#4 Fixed it

### CODE REVIEW

**Comment by JDSustar** [comment]
I think there is a logic error.
- No LED
- Red
- No Star

This should produce a "serial number" scenario. If no serial number is entered, it is green. If either a 1 or 2 is entered, it goes to white.

I found a few other errors similar to this, but I think if this scenario is addressed the others might follow suit.

**Comment by HoferC** [comment]
This should have been fixed in 40c62b3 -- I realized that the logic check for requiring the serial number was actually backwards.

**Comment by JDSustar** [comment]
My fault. I pulled not the latest. We both must have been working on it at the same time.

**Comment by JDSustar** [comment]
:+1:

**Pull request merged**
